### ISSUE TITLE
Milestone 1 Checklist

### ISSUE THREAD

**Issue by zmerpez** [UBC-MDS/DSCI_524_Group19#1]
- [ ] Team work contract
- [ ] Pick a topic
- [ ] Create project structure for the Python project
- [ ] License
- [ ] Edit CONTRIBUTORS.md
- [ ] Edit CONDUCT.md
- [ ] Edit CONTRIBUTING.md 
- [ ] README.md 
- [ ] Function specifications (Remaining 4)
